### ISSUE TITLE
Kpm registry broken

### ISSUE THREAD

**Issue by Opswatch** [dougbtv/openshift-stackanetes#5]
Is the kpm registry working using the ansible playbook?
![openshift22](https://cloud.githubusercontent.com/assets/15094745/22091684/1d5f155a-ddc6-11e6-955d-5eedb647bdcd.JPG) Looks like it does not come up on my machine for some reason - openshift came up with no issues, any ideas?

**Comment by Opswatch** [comment]
Got the error at the end with the following "404 Client Error: Not Found for url: https://beta.kpm.sh/api/v1/packages/coreos/kpm-registry/pull" looks like its due to the beta kpm site not being in use anymore?

**Comment by dougbtv** [comment]
Thanks for the report! For now check out the "kpmreg" branch which should
fix it.

It's pulling from a public kpm registry to bootstrap the  kpm registry, and
the public registry is down. That branch has the fix in to avoid using a
public registry.

Should get a pull into master tomorrow I think.

**Comment by dougbtv** [comment]
Alright PR #6 is merged into master and should fix this up.

Something you might want to do on the failed deploy is run a `oc cluster down` and then run the playbooks again to clear out the namespaces. Some of the roles see if the namespace is there and then skip over the role.

**Comment by Opswatch** [comment]
Comes up now thanks :)

**Comment by dougbtv** [comment]
No prob! Thanks for giving it a go
